CREATE TABLE IF NOT EXISTS equipment_share (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    world TINYINT NOT NULL,
    sharer_name VARCHAR(13) NOT NULL,
    item_id INT NOT NULL,
    is_rare TINYINT DEFAULT 0,
    upgrade_slots TINYINT DEFAULT 0,
    level_ TINYINT DEFAULT 0,
    str_ SMALLINT DEFAULT 0,
    dex_ SMALLINT DEFAULT 0,
    int_ SMALLINT DEFAULT 0,
    luk_ SMALLINT DEFAULT 0,
    hp_ SMALLINT DEFAULT 0,
    mp_ SMALLINT DEFAULT 0,
    watk SMALLINT DEFAULT 0,
    matk SMALLINT DEFAULT 0,
    wdef SMALLINT DEFAULT 0,
    mdef SMALLINT DEFAULT 0,
    acc SMALLINT DEFAULT 0,
    avoid_ SMALLINT DEFAULT 0,
    speed SMALLINT DEFAULT 0,
    jump SMALLINT DEFAULT 0,
    hands SMALLINT DEFAULT 0,
    item_level TINYINT DEFAULT 0,
    vicious SMALLINT DEFAULT 0,
    flag_ SMALLINT DEFAULT 0,
    expiration BIGINT DEFAULT -1,
    req_job SMALLINT DEFAULT 0,
    shared_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_world (world),
    INDEX idx_sharer (world, sharer_name)
);
